services:
  frontend-new:
    image: teanchai1112/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8084:8080" 
    environment:
      - VITE_GRAPHQL_URI=http://34.200.227.74:8083/graphql 
      - VITE_SERVER_URI=http://34.200.227.74/:8083
    restart: unless-stopped